version: "3"

services:
  loginservice:
    image: gargi08092000/loginservice
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:4000|| exit 0"]
      interval: 30s
      timeout: 10s
      retries: 5

  